In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from collections import OrderedDict
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC

In [ ]:
dataset = "https://raw.githubusercontent.com/wahyuarilsaputra/dataset/main/Crop_recommendation.csv"
data = pd.read_csv(dataset)
data

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

# Kategori to Numerik

In [ ]:
dataLabel = data[["label"]]

In [ ]:
numerikLabel = pd.get_dummies(dataLabel)
numerikLabel

label_apple  label_banana  label_blackgram  label_chickpea  \
0               0             0                0               0   
1               0             0                0               0   
2               0             0                0               0   
3               0             0                0               0   
4               0             0                0               0   
...           ...           ...              ...             ...   
2195            0             0                0               0   
2196            0             0                0               0   
2197            0             0                0               0   
2198            0             0                0               0   
2199            0             0                0               0   

      label_coconut  label_coffee  label_cotton  label_grapes  label_jute  \
0                 0             0             0             0           0   
1                 0             0             0             0           0   
2                 0             0             0             0           0   
3                 0             0             0             0           0   
4                 0             0             0             0           0   
...             ...           ...           ...           ...         ...   
2195              0             1             0             0           0   
2196              0             1             0             0           0   
2197              0             1             0             0           0   
2198              0             1             0             0           0   
2199              0             1             0             0           0   

      label_kidneybeans  ...  label_mango  label_mothbeans  label_mungbean  \
0                     0  ...            0                0               0   
1                     0  ...            0                0               0   
2                     0  ...            0                0               0   
3                     0  ...            0                0               0   
4                     0  ...            0                0               0   
...                 ...  ...          ...              ...             ...   
2195                  0  ...            0                0               0   
2196                  0  ...            0                0               0   
2197                  0  ...            0                0               0   
2198                  0  ...            0                0               0   
2199                  0  ...            0                0               0   

      label_muskmelon  label_orange  label_papaya  label_pigeonpeas  \
0                   0             0             0                 0   
1                   0             0             0                 0   
2                   0             0             0                 0   
3                   0             0             0                 0   
4                   0             0             0                 0   
...               ...           ...           ...               ...   
2195                0             0             0                 0   
2196                0             0             0                 0   
2197                0             0             0                 0   
2198                0             0             0                 0   
2199                0             0             0                 0   

      label_pomegranate  label_rice  label_watermelon  
0                     0           1                 0  
1                     0           1                 0  
2                     0           1                 0  
3                     0           1                 0  
4                     0           1                 0  
...                 ...         ...               ...  
2195                  0           0                 0  
2196                  0   

#Normalisasi

In [ ]:
scalerN = MinMaxScaler()
scalerP = MinMaxScaler()
scalerK = MinMaxScaler()
scalerTemperatur = MinMaxScaler()
scalerHumidity = MinMaxScaler()
scalerPh = MinMaxScaler()
scalerRainfall = MinMaxScaler()
scalerData = MinMaxScaler()

In [ ]:
dataNormalisasi = data.drop(columns=['label'])
dataNormalisasi

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [ ]:
dataN = dataNormalisasi[['N']]
dataP = dataNormalisasi[['P']]
dataK = dataNormalisasi[['K']]
dataTemperatur = dataNormalisasi[['temperature']]
dataHumidity = dataNormalisasi[['humidity']]
dataPh = dataNormalisasi[['ph']]
dataRainfall = dataNormalisasi[['rainfall']]

In [ ]:
#normalisasiN
FrameN = scalerN.fit_transform(dataN.values)
hasilN = scalerN.transform(FrameN)
hasilN = scalerN.transform(np.array([[90]]))
hasilN

array([[0.64285714]])

In [ ]:
#normalisasiP
FrameP = scalerP.fit_transform(dataP.values)
hasilP = scalerP.transform(FrameP)
hasilP = scalerP.transform(np.array([[54]]))
hasilP

array([[0.35]])

In [ ]:
#normalisasiK
FrameK = scalerK.fit_transform(dataK.values)
hasilK = scalerK.transform(FrameK)
hasilK = scalerK.transform(np.array([[16]]))
hasilK

array([[0.055]])

In [ ]:
#normalisasiTemperatur
FrameTemperatur = scalerTemperatur.fit_transform(dataTemperatur.values)
hasilTemperatur = scalerTemperatur.transform(FrameTemperatur)
hasilTemperatur = scalerTemperatur.transform(np.array([[22.61359953]]))
hasilTemperatur

array([[0.39563835]])

In [ ]:
#normalisasiHumidity
FrameHumidity = scalerHumidity.fit_transform(dataHumidity.values)
hasilHumidity = scalerHumidity.transform(FrameHumidity)
hasilHumidity = scalerHumidity.transform(np.array([[63.69070564]]))
hasilHumidity

array([[0.57665018]])

In [ ]:
#normalisasiPh
FramePh = scalerPh.fit_transform(dataPh.values)
hasilPh = scalerPh.transform(FramePh)
hasilPh = scalerPh.transform(np.array([[5.7499144210000015]]))
hasilPh

array([[0.34915147]])

In [ ]:
#normalisasiRainfall
FrameRainfall = scalerRainfall.fit_transform(dataRainfall.values)
hasilRainfall = scalerRainfall.transform(FrameRainfall)
hasilRainfall = scalerRainfall.transform(np.array([[87.75953857]]))
hasilRainfall

array([[0.24267487]])

In [ ]:
#NormalisasiSeluruhData
FramehasilNormalisasi = scalerData.fit_transform(dataNormalisasi.values)

In [ ]:
FramehasilNormalisasi

array([[0.64285714, 0.26428571, 0.19      , ..., 0.79026683, 0.46626364,
        0.65645778],
       [0.60714286, 0.37857143, 0.18      , ..., 0.77063285, 0.54948026,
        0.74167459],
       [0.42857143, 0.35714286, 0.195     , ..., 0.79397664, 0.67421877,
        0.87571039],
       ...,
       [0.84285714, 0.2       , 0.125     , ..., 0.61788046, 0.44443315,
        0.55007079],
       [0.83571429, 0.19285714, 0.145     , ..., 0.44175991, 0.50604494,
        0.38428046],
       [0.74285714, 0.09285714, 0.125     , ..., 0.53822177, 0.50931694,
        0.43372112]])

In [ ]:
FramehasilNormalisasi = pd.DataFrame(FramehasilNormalisasi)
FramehasilNormalisasi.columns = ['N','P','K','temperature','humidity','ph','rainfall']
FramehasilNormalisasi

N         P      K  temperature  humidity        ph  rainfall
0     0.642857  0.264286  0.190     0.345886  0.790267  0.466264  0.656458
1     0.607143  0.378571  0.180     0.371445  0.770633  0.549480  0.741675
2     0.428571  0.357143  0.195     0.406854  0.793977  0.674219  0.875710
3     0.528571  0.214286  0.175     0.506901  0.768751  0.540508  0.799905
4     0.557143  0.264286  0.185     0.324378  0.785626  0.641291  0.871231
...        ...       ...    ...          ...       ...       ...       ...
2195  0.764286  0.207143  0.135     0.515037  0.608410  0.509353  0.566064
2196  0.707143  0.071429  0.110     0.533473  0.494359  0.401561  0.386972
2197  0.842857  0.200000  0.125     0.439202  0.617880  0.444433  0.550071
2198  0.835714  0.192857  0.145     0.500627  0.441760  0.506045  0.384280
2199  0.742857  0.092857  0.125     0.424029  0.538222  0.509317  0.433721

[2200 rows x 7 columns]

In [ ]:
label = data['label']
dataHasil = pd.concat([label,FramehasilNormalisasi],axis = 1)
dataHasil

label         N         P      K  temperature  humidity        ph  \
0       rice  0.642857  0.264286  0.190     0.345886  0.790267  0.466264   
1       rice  0.607143  0.378571  0.180     0.371445  0.770633  0.549480   
2       rice  0.428571  0.357143  0.195     0.406854  0.793977  0.674219   
3       rice  0.528571  0.214286  0.175     0.506901  0.768751  0.540508   
4       rice  0.557143  0.264286  0.185     0.324378  0.785626  0.641291   
...      ...       ...       ...    ...          ...       ...       ...   
2195  coffee  0.764286  0.207143  0.135     0.515037  0.608410  0.509353   
2196  coffee  0.707143  0.071429  0.110     0.533473  0.494359  0.401561   
2197  coffee  0.842857  0.200000  0.125     0.439202  0.617880  0.444433   
2198  coffee  0.835714  0.192857  0.145     0.500627  0.441760  0.506045   
2199  coffee  0.742857  0.092857  0.125     0.424029  0.538222  0.509317   

      rainfall  
0     0.656458  
1     0.741675  
2     0.875710  
3     0.799905  
4     0.871231  
...        ...  
2195  0.566064  
2196  0.386972  
2197  0.550071  
2198  0.384280  
2199  0.433721  

[2200 rows x 8 columns]

In [ ]:
percent_amount_of_test_data = 0.3

In [ ]:
matrices_X = dataHasil.iloc[:,1:8].values
matrices_Y = dataHasil.iloc[:,0].values

In [ ]:
X1 = dataHasil.iloc[:,1:8].values
Y1 = dataHasil.iloc[:, 0].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, Y1, test_size = percent_amount_of_test_data, random_state=0)

In [ ]:
### Dictionary to store model and its accuracy

model_accuracy = OrderedDict()

### Dictionary to store model and its precision

model_precision = OrderedDict()

### Dictionary to store model and its recall

model_recall = OrderedDict()

Contoh terdapat Customer dengan nama "Putra"


---

*    Ratio Nitrogen : 0
*    Ratio Phosphorous	: 1
*    Ratio Potassium : 0 
*    Temperature : 0 
*    Humidity : 0 
*    Ph : 0
*    Rainfall    : 0 

Mencari label berdasarkan isi diatas

```
# Contoh Data Customer 'Putra'
[0.64285714, 0.26428571, 0.19, 0.34588614, 0.79026683, 0.46626364, 0.65645778]
```



In [ ]:
#Naive Bayes
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train, y_train)
Y_pred_nb = naive_bayes_classifier.predict(X_test)

cm = confusion_matrix(y_test, Y_pred_nb)

print('Confusion matrix for Gaussian Naive Bayes\n',cm)

naive_bayes_accuracy = round(100 * accuracy_score(y_test, Y_pred_nb), 2)
model_accuracy['Gaussian Naive Bayes'] = naive_bayes_accuracy

naive_bayes_precision = round(100 * precision_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_precision['Gaussian Naive Bayes'] = naive_bayes_precision

naive_bayes_recall = round(100 * recall_score(y_test, Y_pred_nb, average = 'weighted'), 2)
model_recall['Gaussian Naive Bayes'] = naive_bayes_recall

print('The accuracy of this model is {} %.'.format(naive_bayes_accuracy))
print('The precision of this model is {} %.'.format(naive_bayes_precision))
print('The recall of this model is {} %.'.format(naive_bayes_recall))

Confusion matrix for Gaussian Naive Bayes
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 36  0  0  0  0  0  

In [ ]:
naive_bayes_accuracy

99.39

In [ ]:
naive_bayes_accuracy

99.39

In [ ]:
clf = GaussianNB()
clf.fit(matrices_X, matrices_Y)
clf_pf = GaussianNB()
clf_pf.partial_fit(matrices_X, matrices_Y, np.unique(matrices_Y))

GaussianNB()

In [ ]:
FIRST_IDX = 0

In [ ]:
# try with value [0,	0,	0,	0,	0,	0,	1,	0.582609,	0.666667,	0]
result_test_naive_bayes = clf_pf.predict([[0.64285714, 0.26428571, 0.19, 0.34588614, 0.79026683, 0.46626364, 0.65645778]])[FIRST_IDX]
print(f"Customer : Putra Memiliki risk rating {result_test_naive_bayes} Pada metode Gaussian Naive Bayes model")

Customer : Putra Memiliki risk rating rice Pada metode Gaussian Naive Bayes model


In [ ]:
#KNN
K = 10
knn = KNeighborsClassifier(n_neighbors = K)

knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
Y_pred_knn = knn.predict(X_test)

In [ ]:
knn.score(X_test, y_test)

0.9742424242424242

In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_knn)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for K - Nearest Neighbors\n',cm)
nn1_accuracy = round(100 * accuracy_score(y_test, Y_pred_knn), 2)
model_accuracy['1 - Nearest Neighbors'] = nn1_accuracy

nn1_precision = round(100 * precision_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_precision['1 - Nearest Neighbors'] = nn1_precision

nn1_recall = round(100 * recall_score(y_test, Y_pred_knn, average = 'weighted'), 2)
model_recall['1 - Nearest Neighbors'] = nn1_recall

print('The accuracy of this model is {} %.'.format(nn1_accuracy))
print('The precision of this model is {} %.'.format(nn1_precision))
print('The recall of this model is {} %.'.format(nn1_recall))

Confusion matrix for K - Nearest Neighbors
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1  0  1 33  0  0  0  0  0 

In [ ]:
# Custom value to predict
result_test_knn = knn.predict([[0.64285714, 0.26428571, 0.19, 0.34588614, 0.79026683, 0.46626364, 0.65645778]])
print(f"Customer : Putra Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode KNN model")

Customer : Putra Memiliki risk rating rice Pada metode KNN model


In [ ]:
#Decision Tree

decision_tree_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 15)
decision_tree_classifier.fit(X_train, y_train)

Y_pred_dc = decision_tree_classifier.predict(X_test)

In [ ]:
decision_tree_classifier

DecisionTreeClassifier(criterion='entropy', random_state=15)

In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Decision Tree\n',cm)

decision_tree_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Decision Tree'] = decision_tree_accuracy

decision_tree_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Decision Tree'] = decision_tree_precision

decision_tree_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Decision Tree'] = decision_tree_recall

print('The accuracy of this model is {} %.'.format(decision_tree_accuracy))
print('The precision of this model is {} %.'.format(decision_tree_precision))
print('The recall of this model is {} %.'.format(decision_tree_recall))

Confusion matrix for Decision Tree
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  2  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  0 34  0  0  0  0  0  0  0  0

In [ ]:
# Custom value to predict
result_test_knn = decision_tree_classifier.predict([[0.64285714, 0.26428571, 0.19, 0.34588614, 0.79026683, 0.46626364, 0.65645778]])
print(f"Customer : Putra Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode Decision Tree model")

Customer : Putra Memiliki risk rating rice Pada metode Decision Tree model


In [ ]:
datain=[90,	42,	43,	20.879744,	82.002744,	6.502985,	202.935536]

In [ ]:
#Forest
forest = RandomForestClassifier(max_depth=2, random_state=0)
forest.fit(X_train, y_train)

forest

RandomForestClassifier(max_depth=2, random_state=0)

In [ ]:
### Making the confusion matrix
cm = confusion_matrix(y_test, Y_pred_dc)

### Printing the accuracy, precision, and recall of the model
print('Confusion matrix for Random Forest\n',cm)

Random_Forest_accuracy = round(100 * accuracy_score(y_test, Y_pred_dc), 2)
model_accuracy['Random Forest'] = Random_Forest_accuracy

Random_Forest_precision = round(100 * precision_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_precision['Random Forest'] = Random_Forest_precision

Random_Forest_recall = round(100 * recall_score(y_test, Y_pred_dc, average = 'weighted'), 2)
model_recall['Random Forest'] = Random_Forest_recall

print('The accuracy of this model is {} %.'.format(Random_Forest_accuracy))
print('The precision of this model is {} %.'.format(Random_Forest_precision))
print('The recall of this model is {} %.'.format(Random_Forest_recall))

Confusion matrix for Random Forest
 [[28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 30  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 27  0  0  0  0  0  0  0  0  2  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  0 34  0  0  0  0  0  0  0  0

In [ ]:
# Custom value to predict
result_test_forest = forest.predict([[0.64285714, 0.26428571, 0.19, 0.34588614, 0.79026683, 0.46626364, 0.65645778]])
print(f"Customer : Putra Memiliki risk rating {result_test_knn[FIRST_IDX]} Pada metode Random Forest model")

Customer : Putra Memiliki risk rating rice Pada metode Random Forest model


In [ ]:
import pickle

with open('normalisasiNitrogen','wb') as r:
  pickle.dump(scalerN,r)

with open('normalisasiPhosphorous','wb') as r:
  pickle.dump(scalerP,r)

with open('normalisasiPotassium','wb') as r:
  pickle.dump(scalerK,r)

with open('normalisasiTemperature','wb') as r:
  pickle.dump(scalerTemperatur,r)

with open('normalisasiHumidity','wb') as r:
  pickle.dump(scalerHumidity,r)

with open('normalisasiPh','wb') as r:
  pickle.dump(scalerPh,r)

with open('normalisasiRainfall','wb') as r:
  pickle.dump(scalerRainfall,r)

with open('bayes.pickle','wb') as r:
  pickle.dump(naive_bayes_classifier,r)

with open('knn.pickle','wb') as r:
  pickle.dump(knn,r)

with open('decisiontree.pickle','wb') as r:
  pickle.dump(decision_tree_classifier,r)

with open('randomforest.pickle','wb') as r:
  pickle.dump(forest,r)

with open('accBayes.pickle','wb') as r:
  pickle.dump(naive_bayes_accuracy,r)

with open('accTree.pickle','wb') as r:
  pickle.dump(decision_tree_accuracy,r)

with open('accForest.pickle','wb') as r:
  pickle.dump(Random_Forest_accuracy,r)

with open('data.pickle','wb') as r:
  pickle.dump(data,r)

In [ ]:
naive_bayes_accuracy

99.39

In [ ]:
normtes=pickle.load(open('normalisasiNitrogen', 'rb'))